# Generated by Django 5.0 on 2024-05-03 11:18

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_product_preview_alter_order_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt',
            field=models.FileField(null=True, upload_to='orders/receipts'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(null=True, upload_to=shopapp.models.product_preview_directory_path),
        ),
    ]
